Vagrant.configure("2") do |config|
  config.vm.box = "bento/rockylinux-9-arm64"
  config.vm.network "private_network", ip: "10.1.1.11", netmask: "255.255.255.0"
  config.vm.hostname = "ezconf.tp1.efrei"
  config.vm.provision "shell", path: "script.sh" 
  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "2048"
    v.vmx["name"] = "ezconf.tp1.efrei"
    # Impossible d'allouer une taille spécifique de disque sur fusion 🙃
  end
end
